name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Remove conflicting containerd package
        run: sudo apt-get remove containerd

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker

      - name: Install node modules
        run: npm ci

      - name: Build project
        run: npm run build:prod

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Build storybook
        run: npm run storybook:build

      - name: Run screenshot test
        run: npm run test:ui:ci
